services:
  angular_frontend:
    container_name: doc-mgmt-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm start"
